"""Server-generated exports: bid comparison (xlsx), award memo (pdf), audit (csv)."""
import csv
import io

from django.http import HttpResponse

from .models import Bid, Event, Supplier, Tender
from .util import fmt_date_ms, total_score
from .views import CHAIR_ROLES, err, route


def _file(data, name, ctype):
    r = HttpResponse(data, content_type=ctype)
    r["Content-Disposition"] = f'attachment; filename="{name}"'
    return r


@route(["GET"], roles=CHAIR_ROLES)
def export_comparison(request, p, body, tid):
    t = Tender.objects.filter(pk=tid).first()
    if not t:
        return err("Tender not found.", 404)
    if not t.opened_at:
        return err("The comparison exists only after the recorded opening.", 409)
    from openpyxl import Workbook
    from openpyxl.styles import Font
    wb = Workbook()
    ws = wb.active
    ws.title = "Comparison"
    bold = Font(bold=True)
    ws.append([f"{t.ref} — {t.title}"]); ws["A1"].font = Font(bold=True, size=13)
    ws.append([f"Budget ceiling: {t.budget:,} · Opened: {fmt_date_ms(t.opened_at)}"])
    ws.append([])
    sups = {s.id: s.name for s in Supplier.objects.all()}
    bids = list(Bid.objects.filter(tender=t).order_by("submitted_at"))
    head = ["Supplier", "Amount", "vs budget"]
    if t.lines:
        head += [f"{l['desc']} (x{l['qty']})" for l in t.lines]
    head += ["Weighted score", "Awarded"]
    ws.append(head)
    for c in ws[4]:
        c.font = bold
    for b in bids:
        row = [sups.get(b.supplier_id, b.supplier_id), b.amount,
               f"{(b.amount - t.budget) / t.budget * 100:+.1f}%"]
        if t.lines:
            row += [(b.lines or {}).get(l["id"], "") for l in t.lines]
        ts = total_score(t, b, bids)
        row += [round(ts, 2) if ts is not None else "not scored",
                "YES" if t.awarded_to == b.supplier_id else ""]
        ws.append(row)
    for col in ws.columns:
        ws.column_dimensions[col[0].column_letter].width = max(14, min(38, max(len(str(c.value or "")) for c in col) + 2))
    buf = io.BytesIO()
    wb.save(buf)
    return _file(buf.getvalue(), f"{t.ref}-comparison.xlsx",
                 "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")


@route(["GET"], roles=CHAIR_ROLES)
def export_memo(request, p, body, tid):
    t = Tender.objects.filter(pk=tid).first()
    if not t:
        return err("Tender not found.", 404)
    memo = t.award_memo or (t.award_rec or {}).get("memo")
    if not memo:
        return err("No award memo exists yet.", 409)
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=22 * mm, rightMargin=22 * mm,
                            topMargin=20 * mm, bottomMargin=20 * mm, title=f"{t.ref} award memo")
    h = ParagraphStyle("h", fontName="Times-Bold", fontSize=15, spaceAfter=4)
    sub = ParagraphStyle("sub", fontName="Courier", fontSize=8.5, textColor="#666666", spaceAfter=14)
    body_style = ParagraphStyle("b", fontName="Times-Roman", fontSize=10.5, leading=15)
    flow = [Paragraph("AWARD RECOMMENDATION MEMORANDUM", h),
            Paragraph(f"{t.ref} · generated by DOCKET · exported by {p['name']}", sub)]
    for para in memo.split("\n\n"):
        flow += [Paragraph(para.replace("\n", "<br/>"), body_style), Spacer(1, 8)]
    doc.build(flow)
    return _file(buf.getvalue(), f"{t.ref}-award-memo.pdf", "application/pdf")


@route(["GET"], roles={"auditor", "procurement", "approver"})
def export_audit(request, p, body):
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["seq", "at", "actor", "role", "action", "tender", "detail", "prev_hash", "hash"])
    for e in Event.objects.order_by("seq"):
        w.writerow([e.seq, fmt_date_ms(e.at), e.actor, e.role, e.action, e.tender_id or "", e.detail,
                    e.prev_hash, e.hash])
    return _file(buf.getvalue().encode(), "docket-audit-trail.csv", "text/csv")
