from django.urls import path

from . import account_views, admin_views, auth_views, export_views, finance_views, views

# The administration console. Its own sign-in, its own token check (superuser or
# nothing), and no link to it anywhere in the tendering UI.
admin_urlpatterns = [
    path("admin/login/", admin_views.admin_login),
    path("admin/logout/", admin_views.admin_logout),
    path("admin/state/", admin_views.admin_state),
    path("admin/log/", admin_views.admin_log),
    path("admin/roles/", admin_views.admin_create_role),
    path("admin/roles/<str:key>/", admin_views.admin_update_role),
    path("admin/roles/<str:key>/delete/", admin_views.admin_delete_role),
    path("admin/users/", admin_views.admin_create_user),
    path("admin/users/perms/", admin_views.admin_set_perms),
    path("admin/users/<int:uid>/", admin_views.admin_update_user),
    path("admin/users/<int:uid>/password/", admin_views.admin_reset_password),
    path("admin/users/<int:uid>/sessions/", admin_views.admin_sessions),
    path("admin/users/<int:uid>/mfa_reset/", admin_views.admin_reset_mfa),
    path("admin/users/<int:uid>/delete/", admin_views.admin_delete_user),
]

urlpatterns = admin_urlpatterns + [
    path("health/", views.health),
    path("auth/config/", auth_views.auth_config),
    path("auth/login/", auth_views.login),
    path("auth/demo/", auth_views.demo_login),
    path("auth/logout/", auth_views.logout),
    path("auth/logout_all/", auth_views.logout_all),
    path("auth/mfa/", auth_views.mfa_status),
    path("auth/mfa/setup/", auth_views.mfa_setup),
    path("auth/mfa/enable/", auth_views.mfa_enable),
    path("auth/mfa/disable/", auth_views.mfa_disable),
    path("auth/forgot/", account_views.forgot_password),
    path("auth/reset_password/", account_views.reset_password),
    path("register/vendor/", account_views.register_vendor),
    path("register/claim/", account_views.claim_vendor),
    path("register/verify/", account_views.verify_vendor),
    path("register/accept_invite/", account_views.accept_invite),

    path("bootstrap/", views.bootstrap),
    path("finance/", finance_views.finance_state),
    path("finance/exceptions/", finance_views.finance_exceptions),
    path("finance/import/", finance_views.finance_import),
    path("finance/baseline/", finance_views.baseline_suggestion),
    path("finance/baselines/", finance_views.baseline_backfill),
    path("reset/", views.reset_demo),
    path("notifications/read/", views.mark_notifications_read),

    path("tenders/", views.tender_create),
    path("tenders/<str:tid>/", views.tender_update),
    path("tenders/<str:tid>/submit/", views.tender_submit),
    path("tenders/<str:tid>/publish_decision/", views.publish_decision),
    path("tenders/<str:tid>/addenda/", views.add_addendum),
    path("tenders/<str:tid>/open/", views.open_bids),
    path("tenders/<str:tid>/recommend/", views.recommend_award),
    path("tenders/<str:tid>/withdraw_recommendation/", views.withdraw_recommendation),
    path("tenders/<str:tid>/award_decision/", views.award_decision),
    path("tenders/<str:tid>/bids/", views.bid_collection),
    path("tenders/<str:tid>/clarifications/", views.ask_clarification),
    path("tenders/<str:tid>/coi/", views.declare_coi),
    path("tenders/<str:tid>/auction/", views.auction_state),
    path("tenders/<str:tid>/auction/bids/", views.auction_bid),
    path("tenders/<str:tid>/docs/", views.upload_tender_doc),
    path("tenders/<str:tid>/bid_docs/", views.upload_bid_doc),
    path("docs/<str:doc_id>/", views.delete_doc),
    path("me/", views.me_update),
    path("me/docs/", views.upload_supplier_doc),
    path("me/docs/<str:doc_id>/", views.delete_supplier_doc),
    path("team/", views.team),
    path("team/invite/", views.invite_team),
    path("suppliers/invite/", views.invite_vendor),
    path("suppliers/campaign/", views.vendor_campaign),
    path("suppliers/import/", views.import_suppliers),
    path("suppliers/import_register/", views.import_register),
    path("team/org/", views.set_reporting_line),
    path("settings/", views.settings_view),
    path("tenders/<str:tid>/duplicate/", views.duplicate_tender),
    path("tenders/<str:tid>/export/compliance.pdf", views.export_compliance),
    path("audit/integrity/", views.chain_integrity),
    path("tenders/<str:tid>/export/comparison.xlsx", export_views.export_comparison),
    path("tenders/<str:tid>/export/memo.pdf", export_views.export_memo),
    path("export/audit.csv", export_views.export_audit),
    path("docs/<str:doc_id>/download/", views.download_doc),

    path("bids/<str:bid_id>/scores/", views.save_scores),
    path("clarifications/<str:cid>/answer/", views.answer_clarification),
    path("suppliers/<str:sid>/", views.supplier_detail),
    path("suppliers/<str:sid>/prequalify/", views.prequalify),

    path("ai/scope/", views.ai_scope),
    path("ai/criteria/", views.ai_criteria),
    path("ai/insights/", views.ai_insights),
    path("ai/clarifications/<str:cid>/answer/", views.ai_clar_answer),
    path("ai/tenders/<str:tid>/brief/", views.ai_brief),
    path("ai/tenders/<str:tid>/bid_review/", views.ai_bid_review),
]
