from django.urls import path

from . import account_views, auth_views, export_views, views

urlpatterns = [
    path("health/", views.health),
    path("auth/config/", auth_views.auth_config),
    path("auth/login/", auth_views.login),
    path("auth/demo/", auth_views.demo_login),
    path("auth/logout/", auth_views.logout),
    path("auth/logout_all/", auth_views.logout_all),
    path("auth/mfa/", auth_views.mfa_status),
    path("auth/mfa/setup/", auth_views.mfa_setup),
    path("auth/mfa/enable/", auth_views.mfa_enable),
    path("auth/mfa/disable/", auth_views.mfa_disable),
    path("auth/forgot/", account_views.forgot_password),
    path("auth/reset_password/", account_views.reset_password),
    path("register/vendor/", account_views.register_vendor),
    path("register/verify/", account_views.verify_vendor),
    path("register/accept_invite/", account_views.accept_invite),

    path("bootstrap/", views.bootstrap),
    path("reset/", views.reset_demo),
    path("notifications/read/", views.mark_notifications_read),

    path("tenders/", views.tender_create),
    path("tenders/<str:tid>/", views.tender_update),
    path("tenders/<str:tid>/submit/", views.tender_submit),
    path("tenders/<str:tid>/publish_decision/", views.publish_decision),
    path("tenders/<str:tid>/addenda/", views.add_addendum),
    path("tenders/<str:tid>/open/", views.open_bids),
    path("tenders/<str:tid>/recommend/", views.recommend_award),
    path("tenders/<str:tid>/withdraw_recommendation/", views.withdraw_recommendation),
    path("tenders/<str:tid>/award_decision/", views.award_decision),
    path("tenders/<str:tid>/bids/", views.bid_collection),
    path("tenders/<str:tid>/clarifications/", views.ask_clarification),
    path("tenders/<str:tid>/coi/", views.declare_coi),
    path("tenders/<str:tid>/auction/", views.auction_state),
    path("tenders/<str:tid>/auction/bids/", views.auction_bid),
    path("tenders/<str:tid>/docs/", views.upload_tender_doc),
    path("tenders/<str:tid>/bid_docs/", views.upload_bid_doc),
    path("docs/<str:doc_id>/", views.delete_doc),
    path("me/", views.me_update),
    path("me/docs/", views.upload_supplier_doc),
    path("me/docs/<str:doc_id>/", views.delete_supplier_doc),
    path("team/", views.team),
    path("team/invite/", views.invite_team),
    path("suppliers/invite/", views.invite_vendor),
    path("suppliers/import/", views.import_suppliers),
    path("settings/", views.settings_view),
    path("tenders/<str:tid>/duplicate/", views.duplicate_tender),
    path("tenders/<str:tid>/export/compliance.pdf", views.export_compliance),
    path("audit/integrity/", views.chain_integrity),
    path("tenders/<str:tid>/export/comparison.xlsx", export_views.export_comparison),
    path("tenders/<str:tid>/export/memo.pdf", export_views.export_memo),
    path("export/audit.csv", export_views.export_audit),
    path("docs/<str:doc_id>/download/", views.download_doc),

    path("bids/<str:bid_id>/scores/", views.save_scores),
    path("clarifications/<str:cid>/answer/", views.answer_clarification),
    path("suppliers/<str:sid>/prequalify/", views.prequalify),

    path("ai/scope/", views.ai_scope),
    path("ai/criteria/", views.ai_criteria),
    path("ai/insights/", views.ai_insights),
    path("ai/clarifications/<str:cid>/answer/", views.ai_clar_answer),
    path("ai/tenders/<str:tid>/brief/", views.ai_brief),
    path("ai/tenders/<str:tid>/bid_review/", views.ai_bid_review),
]
