# Generated by Django 5.2.16 on 2026-07-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('at', models.BigIntegerField()),
                ('actor', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=120)),
                ('tender_id', models.CharField(blank=True, max_length=16, null=True)),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('rating', models.FloatField(default=0)),
                ('prequalified', models.BooleanField(default=False)),
                ('docs', models.JSONField(default=list)),
                ('perf', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('ttype', models.CharField(max_length=8)),
                ('category', models.CharField(max_length=60)),
                ('budget', models.BigIntegerField()),
                ('status', models.CharField(max_length=16)),
                ('published_at', models.BigIntegerField(blank=True, null=True)),
                ('deadline', models.BigIntegerField()),
                ('opened_at', models.BigIntegerField(blank=True, null=True)),
                ('awarded_at', models.BigIntegerField(blank=True, null=True)),
                ('awarded_to', models.CharField(blank=True, max_length=16, null=True)),
                ('awarded_amount', models.BigIntegerField(blank=True, null=True)),
                ('award_memo', models.TextField(blank=True, default='')),
                ('tech_weight', models.IntegerField(default=70)),
                ('comm_weight', models.IntegerField(default=30)),
                ('scope', models.TextField(blank=True, default='')),
                ('criteria', models.JSONField(default=list)),
                ('lines', models.JSONField(default=list)),
                ('addenda', models.JSONField(default=list)),
                ('invited', models.JSONField(default=list)),
                ('award_rec', models.JSONField(blank=True, null=True)),
                ('letters', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clarification',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('supplier_id', models.CharField(max_length=16)),
                ('q', models.TextField()),
                ('asked_at', models.BigIntegerField()),
                ('a', models.TextField(blank=True, null=True)),
                ('answered_at', models.BigIntegerField(blank=True, null=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='core.tender')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('supplier_id', models.CharField(max_length=16)),
                ('submitted_at', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('lines', models.JSONField(default=dict)),
                ('scores', models.JSONField(default=dict)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.tender')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tender', 'supplier_id'), name='one_bid_per_supplier')],
            },
        ),
    ]
