# Generated by Django 5.2.16 on 2026-07-24 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMark',
            fields=[
                ('key', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('at', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='notes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tender',
            name='coi',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created', models.BigIntegerField()),
                ('last_used', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=12)),
                ('supplier_id', models.CharField(blank=True, max_length=16, null=True)),
                ('envelope', models.CharField(blank=True, default='', max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('content_type', models.CharField(blank=True, default='application/octet-stream', max_length=120)),
                ('size', models.IntegerField()),
                ('data', models.BinaryField()),
                ('uploaded_by', models.CharField(max_length=120)),
                ('uploaded_at', models.BigIntegerField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.tender')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('at', models.BigIntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('tender_id', models.CharField(blank=True, max_length=16, null=True)),
                ('read', models.BooleanField(default=False)),
                ('emailed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
