# Generated by Django 5.2.16 on 2026-07-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taskmark_bid_notes_tender_coi_authtoken_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionToken',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('created', models.BigIntegerField()),
                ('used_at', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChainHead',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('seq', models.IntegerField(default=0)),
                ('hash', models.CharField(default='genesis', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='sealed_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='expiry',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='seq',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.tender'),
        ),
    ]
