# Generated by Django 5.2.16 on 2026-07-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actiontoken_chainhead_bid_sealed_blob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registered_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rejected_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
