# Generated by Django 5.2.16 on 2026-07-25 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supplier_contact_email_supplier_registered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='auction_min_decrement',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tender',
            name='tech_opened_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='tech_threshold',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='tender',
            name='two_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('supplier_id', models.CharField(max_length=16)),
                ('amount', models.BigIntegerField()),
                ('at', models.BigIntegerField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to='core.tender')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
    ]
