# Generated by Django 5.2.16 on 2026-07-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bid_disqualified_tender_auction_min_decrement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSetting',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
