# Generated by Django 5.2.16 on 2026-07-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orgsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=200)),
                ('at', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
