# Generated by Django 5.2.16 on 2026-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vendor_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('title', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('perms', models.JSONField(default=list)),
                ('created', models.BigIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='AdminAudit',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('at', models.BigIntegerField()),
                ('actor', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=140)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='perm_extra',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='perm_revoked',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
