# Generated by Django 5.2.16 on 2026-08-06 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backfill_taxonomy_and_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('source', models.CharField(default='nav', max_length=12)),
                ('external_id', models.CharField(blank=True, default='', max_length=80)),
                ('synced_at', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('amount_src', models.BigIntegerField(default=0)),
                ('fx_rate', models.FloatField(default=1.0)),
                ('ref', models.CharField(max_length=60)),
                ('received_at', models.BigIntegerField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='exposure_limit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tender',
            name='cost_centre',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='tender',
            name='department',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tender',
            name='funding_source',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tender',
            name='project',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tender',
            name='region',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('department', models.CharField(blank=True, default='', max_length=80)),
                ('cost_centre', models.CharField(blank=True, default='', max_length=40)),
                ('project', models.CharField(blank=True, default='', max_length=120)),
                ('region', models.CharField(blank=True, default='', max_length=60)),
                ('funding_source', models.CharField(blank=True, default='', max_length=80)),
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('source', models.CharField(default='nav', max_length=12)),
                ('external_id', models.CharField(blank=True, default='', max_length=80)),
                ('synced_at', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('amount_src', models.BigIntegerField(default=0)),
                ('fx_rate', models.FloatField(default=1.0)),
                ('ref', models.CharField(max_length=60)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('original_value', models.BigIntegerField(default=0)),
                ('signed_at', models.BigIntegerField(blank=True, null=True)),
                ('starts_at', models.BigIntegerField(blank=True, null=True)),
                ('ends_at', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('change_orders', models.JSONField(blank=True, default=list)),
                ('renewal_notice_days', models.IntegerField(default=90)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.supplier')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.tender')),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('at', models.BigIntegerField()),
                ('rate', models.FloatField()),
                ('source', models.CharField(default='nav', max_length=12)),
            ],
            options={
                'ordering': ['-at'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'at'), name='one_rate_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('source', models.CharField(default='nav', max_length=12)),
                ('external_id', models.CharField(blank=True, default='', max_length=80)),
                ('synced_at', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('amount_src', models.BigIntegerField(default=0)),
                ('fx_rate', models.FloatField(default=1.0)),
                ('supplier_ref', models.CharField(blank=True, default='', max_length=80)),
                ('invoiced_at', models.BigIntegerField(blank=True, null=True)),
                ('received_at', models.BigIntegerField(blank=True, null=True)),
                ('due_at', models.BigIntegerField(blank=True, null=True)),
                ('approved_at', models.BigIntegerField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(default='received', max_length=16)),
                ('hold_reason', models.CharField(blank=True, default='', max_length=200)),
                ('discount_pct', models.FloatField(default=0)),
                ('discount_days', models.IntegerField(default=0)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.contract')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.goodsreceipt')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.supplier')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('source', models.CharField(default='nav', max_length=12)),
                ('external_id', models.CharField(blank=True, default='', max_length=80)),
                ('synced_at', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('amount_src', models.BigIntegerField(default=0)),
                ('fx_rate', models.FloatField(default=1.0)),
                ('ref', models.CharField(max_length=60)),
                ('paid_at', models.BigIntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, default='', max_length=24)),
                ('discount_taken', models.BigIntegerField(default=0)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.invoice')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.supplier')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('source', models.CharField(default='nav', max_length=12)),
                ('external_id', models.CharField(blank=True, default='', max_length=80)),
                ('synced_at', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('amount_src', models.BigIntegerField(default=0)),
                ('fx_rate', models.FloatField(default=1.0)),
                ('ref', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('raised_at', models.BigIntegerField(blank=True, null=True)),
                ('raised_by', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(default='open', max_length=16)),
                ('approved_at', models.BigIntegerField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=120)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.contract')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.supplier')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.tender')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='core.purchaseorder'),
        ),
        migrations.CreateModel(
            name='SourceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=12)),
                ('entity', models.CharField(max_length=24)),
                ('last_attempt', models.BigIntegerField(default=0)),
                ('last_success', models.BigIntegerField(default=0)),
                ('rows_seen', models.IntegerField(default=0)),
                ('rows_written', models.IntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'entity'), name='one_sync_per_feed')],
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='one_contract_per_external_id'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='one_payment_per_external_id'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='one_po_per_external_id'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='one_invoice_per_external_id'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='one_grn_per_external_id'),
        ),
    ]
