# Generated by Django 5.2.16 on 2026-08-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_p2p_ledger_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoFixture',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('at', models.BigIntegerField(default=0)),
                ('manifest', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
