# Generated by Django 5.2.16 on 2026-08-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_demofixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('source', models.CharField(default='nav', max_length=12)),
                ('external_id', models.CharField(blank=True, default='', max_length=80)),
                ('synced_at', models.BigIntegerField(default=0)),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('description2', models.CharField(blank=True, default='', max_length=200)),
                ('uom', models.CharField(blank=True, default='', max_length=24)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('unit_cost', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('blocked', models.BooleanField(default=False)),
                ('kind', models.CharField(blank=True, default='', max_length=24)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='one_item_per_external_id')],
            },
        ),
    ]
