# Generated by Django 5.2.16 on 2026-09-08 23:02

import django.db.models.deletion
from django.db import migrations, models


def _backfill(apps, schema_editor):
    """Vendors already on the register carry their history forward.

    `verified_at` is new, but the decision it dates is not: a vendor with
    `prequalified` set was verified at some point, and the nearest honest date
    we hold is when they registered. Left null where even that is unknown -
    an invented date on an audit record is worse than an absent one.

    `source` is inferred the same way: a registration timestamp means they came
    through registration, an invitation without one means the invite is still
    outstanding, and everything else arrived in a register import.
    """
    Supplier = apps.get_model("core", "Supplier")
    for s in Supplier.objects.all().iterator():
        changed = []
        if s.prequalified and not s.verified_at and s.registered_at:
            s.verified_at = s.registered_at
            changed.append("verified_at")
        if not s.source:
            s.source = "self" if s.registered_at else ("invite" if s.invited_at else "import")
            changed.append("source")
        if changed:
            s.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRound',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('opens_at', models.BigIntegerField(blank=True, null=True)),
                ('deadline', models.BigIntegerField(blank=True, null=True)),
                ('opened_at', models.BigIntegerField(blank=True, null=True)),
                ('closed_at', models.BigIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, default='')),
                ('invited', models.JSONField(blank=True, default=list)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.BigIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'ordering': ['tender_id', 'number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='bid',
            name='one_bid_per_supplier',
        ),
        migrations.AddField(
            model_name='supplier',
            name='source',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='suspended_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='suspended_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='supplier',
            name='verified_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='verified_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tender',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tender',
            name='cancelled_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='deadline_changes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tender',
            name='paused_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='paused_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tender',
            name='projected_cost',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='resumed_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementround',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.tender'),
        ),
        migrations.AddField(
            model_name='bid',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.procurementround'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('tender', 'supplier_id', 'round'), name='one_bid_per_supplier_round'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(condition=models.Q(('round__isnull', True)), fields=('tender', 'supplier_id'), name='one_bid_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='procurementround',
            constraint=models.UniqueConstraint(fields=('tender', 'number'), name='one_round_per_number'),
        ),
        migrations.RunPython(_backfill, migrations.RunPython.noop),
    ]
