# Generated by Django 5.2.16 on 2026-09-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_procurement_rounds_and_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.procurementround'),
        ),
    ]
