# Generated by Django 5.2.16 on 2026-09-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_document_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='approval_level',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=12)),
                ('seq', models.IntegerField()),
                ('level_id', models.CharField(max_length=16)),
                ('level_name', models.CharField(max_length=80)),
                ('level_limit', models.BigIntegerField(default=0)),
                ('role', models.CharField(blank=True, default='', max_length=40)),
                ('holders', models.JSONField(blank=True, default=list)),
                ('amount', models.BigIntegerField(default=0)),
                ('opened_at', models.BigIntegerField()),
                ('decided_at', models.BigIntegerField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, default='', max_length=120)),
                ('decision', models.CharField(blank=True, default='', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to='core.persona')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='core.tender')),
            ],
            options={
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['tender', 'kind', 'seq'], name='core_approv_tender__2db296_idx')],
            },
        ),
    ]
