# Generated by Django 5.2.16 on 2026-09-22 08:28

import core.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_persona_approval_level_approvalstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.CharField(default=core.util.rid, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('prefix', models.CharField(db_index=True, max_length=24)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('created', models.BigIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('last_used', models.BigIntegerField(default=0)),
                ('calls', models.BigIntegerField(default=0)),
                ('revoked_at', models.BigIntegerField(blank=True, null=True)),
                ('window_at', models.BigIntegerField(default=0)),
                ('window_calls', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tombstone',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.CharField(db_index=True, max_length=32)),
                ('row_id', models.CharField(max_length=64)),
                ('at', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='updated_at',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='updated_at',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='persona',
            name='updated_at',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='tender',
            name='updated_at',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
