# Generated by Django 5.2.16 on 2026-09-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_backfill_sync_cursor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('updated_at', models.BigIntegerField(db_index=True, default=0)),
                ('department', models.CharField(blank=True, default='', max_length=80)),
                ('cost_centre', models.CharField(blank=True, default='', max_length=40)),
                ('project', models.CharField(blank=True, default='', max_length=120)),
                ('region', models.CharField(blank=True, default='', max_length=60)),
                ('funding_source', models.CharField(blank=True, default='', max_length=80)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('scope', models.TextField(blank=True, default='')),
                ('terms', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='draft', max_length=12)),
                ('visibility', models.CharField(default='rank', max_length=8)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('starts_at', models.BigIntegerField(blank=True, null=True)),
                ('scheduled_ends_at', models.BigIntegerField(blank=True, null=True)),
                ('ends_at', models.BigIntegerField(blank=True, null=True)),
                ('closed_at', models.BigIntegerField(blank=True, null=True)),
                ('snipe_window_ms', models.BigIntegerField(default=120000)),
                ('extend_by_ms', models.BigIntegerField(default=120000)),
                ('max_extensions', models.IntegerField(default=20)),
                ('extensions', models.JSONField(blank=True, default=list)),
                ('ceiling_visible', models.BooleanField(default=True)),
                ('require_acceptance', models.BooleanField(default=True)),
                ('created_at', models.BigIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('paused_at', models.BigIntegerField(blank=True, null=True)),
                ('paused_reason', models.CharField(blank=True, default='', max_length=300)),
                ('resumed_at', models.BigIntegerField(blank=True, null=True)),
                ('cancelled_at', models.BigIntegerField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=300)),
                ('awarded_at', models.BigIntegerField(blank=True, null=True)),
                ('awarded_by', models.CharField(blank=True, default='', max_length=120)),
                ('award_memo', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_auctions', to='core.persona')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('updated_at', models.BigIntegerField(db_index=True, default=0)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('qty', models.BigIntegerField(default=1)),
                ('uom', models.CharField(blank=True, default='', max_length=24)),
                ('ceiling', models.BigIntegerField(default=0)),
                ('reserve', models.BigIntegerField(blank=True, null=True)),
                ('min_decrement', models.BigIntegerField(default=0)),
                ('decrement_is_pct', models.BooleanField(default=False)),
                ('status', models.CharField(default='open', max_length=12)),
                ('awarded_to', models.CharField(blank=True, default='', max_length=16)),
                ('awarded_amount', models.BigIntegerField(blank=True, null=True)),
                ('awarded_at', models.BigIntegerField(blank=True, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.auction')),
            ],
            options={
                'ordering': ['auction', 'number'],
            },
        ),
        migrations.CreateModel(
            name='AuctionParticipant',
            fields=[
                ('updated_at', models.BigIntegerField(db_index=True, default=0)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('supplier_id', models.CharField(max_length=16)),
                ('invited_at', models.BigIntegerField(blank=True, null=True)),
                ('invite_count', models.IntegerField(default=0)),
                ('invite_error', models.CharField(blank=True, default='', max_length=200)),
                ('accepted_at', models.BigIntegerField(blank=True, null=True)),
                ('joined_at', models.BigIntegerField(blank=True, null=True)),
                ('withdrawn_at', models.BigIntegerField(blank=True, null=True)),
                ('disqualified', models.BooleanField(default=False)),
                ('disqualified_reason', models.CharField(blank=True, default='', max_length=300)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.auction')),
            ],
            options={
                'ordering': ['auction', 'supplier_id'],
            },
        ),
        migrations.CreateModel(
            name='LotBid',
            fields=[
                ('updated_at', models.BigIntegerField(db_index=True, default=0)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('supplier_id', models.CharField(db_index=True, max_length=16)),
                ('amount', models.BigIntegerField()),
                ('at', models.BigIntegerField()),
                ('kind', models.CharField(default='manual', max_length=8)),
                ('closes_at_bid_time', models.BigIntegerField(default=0)),
                ('extended', models.BooleanField(default=False)),
                ('retracted_at', models.BigIntegerField(blank=True, null=True)),
                ('retracted_reason', models.CharField(blank=True, default='', max_length=300)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.auction')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.auctionlot')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProxyBid',
            fields=[
                ('updated_at', models.BigIntegerField(db_index=True, default=0)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('supplier_id', models.CharField(max_length=16)),
                ('floor', models.BigIntegerField()),
                ('created_at', models.BigIntegerField(default=0)),
                ('cancelled_at', models.BigIntegerField(blank=True, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='core.auctionlot')),
            ],
            options={
                'ordering': ['lot', 'supplier_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='auctionlot',
            constraint=models.UniqueConstraint(fields=('auction', 'number'), name='one_lot_number_per_auction'),
        ),
        migrations.AddConstraint(
            model_name='auctionparticipant',
            constraint=models.UniqueConstraint(fields=('auction', 'supplier_id'), name='one_participant_per_auction'),
        ),
        migrations.AddIndex(
            model_name='lotbid',
            index=models.Index(fields=['lot', 'amount'], name='core_lotbid_lot_id_f7eceb_idx'),
        ),
        migrations.AddConstraint(
            model_name='proxybid',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('lot', 'supplier_id'), name='one_live_proxy_per_lot'),
        ),
    ]
