# Generated by Django 5.2.16 on 2026-09-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auctions_leave_tenders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='auction_min_decrement',
        ),
        migrations.DeleteModel(
            name='AuctionBid',
        ),
    ]
