# Generated by Django 5.2.16 on 2026-09-29 09:30

from django.db import migrations, models


def link_existing_auction_alerts(apps, schema_editor):
    Notification = apps.get_model("core", "Notification")
    Auction = apps.get_model("core", "Auction")
    db = schema_editor.connection.alias
    auctions = list(Auction.objects.using(db).values("id", "ref", "title"))
    for notice in Notification.objects.using(db).filter(
            subject__startswith="Invitation to a reverse auction:").iterator():
        matches = [a for a in auctions
                   if notice.subject == f"Invitation to a reverse auction: {a['title']}"[:200]
                   and f"{a['ref']} - {a['title']}" in notice.body]
        if len(matches) == 1:
            notice.destination = {"page": "auction", "id": matches[0]["id"]}
            notice.save(using=db, update_fields=["destination"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auctions_leave_tenders_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='destination',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(link_existing_auction_alerts, migrations.RunPython.noop),
    ]
