# Generated by Django 5.2.16 on 2026-10-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_notification_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.auction'),
        ),
    ]
