# Generated by Django 5.2.16 on 2026-10-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_grant_team_roles_to_setup_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='direction',
            field=models.CharField(choices=[('reverse', 'Buying: lowest wins'), ('sale', 'Selling: highest wins')], default='reverse', max_length=8),
        ),
    ]
