# Generated by Django 5.2.16 on 2026-10-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auction_selling_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='bidder_mode',
            field=models.BooleanField(default=False),
        ),
    ]
