# Generated by Django 5.2.16 on 2026-10-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_require_temporary_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='commercial_document_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='technical_document_required',
            field=models.BooleanField(default=True),
        ),
    ]
